### PR TITLE
Linear system solving via QR column pivoting

### PR DESCRIPTION
**Pull request by YoshuaNava**
Fix for issue #7

I replaced the current line parameters matrix solution, with Eigen's [QR column pivoting](https://eigen.tuxfamily.org/dox/classEigen_1_1ColPivHouseholderQR.html).

I chose this method instead of the others present on Eigen because of its accuracy and speed without placing any strong requirements on the system matrices ([source](https://eigen.tuxfamily.org/dox/group__TutorialLinearAlgebra.html))

### CODE REVIEW

**Comment by lorenwel** [comment]
Have  you benchmarked this change against the prior version in terms of speed?
If this is significantly slower I would prefer to investigate the interaction with eigen_gtsam and why this happens in the first place.

**Comment by YoshuaNava** [comment]
I made a quick benchmark over two datasets. The first dataset uses a Velodyne VLP-16, and the second a HDL-64E (KITTI). I estimated the ratio between the elapsed times of the matrix and QR pivoting methods.

ratio = time_matrix / time_qrpiv;

These were the results I got with the VLP-16 dataset:

alt text

And these the ones I got with the HDL-64E:

alt text

There is a speed-up of at least ~4x with the QR column pivoting method. In some specific cases the matrix method is faster, though, as it can be seen in the graphs, for the points with a ratio less than 1. 

I pushed the code I used for this tests to [the branch](https://github.com/yoshua-msc-thesis/linefit_ground_segmentation/tree/fix/linear_system_pivoting) I keep for this pull request.

(the quality of the plots may not be the best, sorry for that)

**Comment by lorenwel** [comment]
Thanks for the extensive analysis. We should use the QR solver then. 
I don't think the files for your analysis should be part of the analysis. Could you please revert your last commit so I can merge the solver changes only.

**Comment by YoshuaNava** [comment]
No problem. Glad to contribute. This package was very useful for my work.

Sorry. I should have committed the scripts in a different branch. I'll revert the last commit now.

**Pull request merged**
